from datos_basicos import *
U1=datos_basicos()
print()
print('DATOS DE IDENTIFICACION')
U1.set_datos_identificacion(str(input('ingrese si tiene Ti o CC: \n')))
U1.set_datos_identificacion(int(input('ingrese su numero de documento: \n')))
print(U1.get_datos_identificacion())
"""ubicacion"""
print()
print('IDENTIDAD')
U1.set_identidad(str(input('ingrese sus nombres: \n')))
U1.set_identidad(str(input('ingrese su primer apellido: \n')))
U1.set_identidad(str(input('ingrese su segundo apellido: \n')))
U1.set_identidad(str(input('genero: \n')))
print(U1.get_identidad())
print()
print('DATOS DE NACIMIENTO')
U1.set_datos_nacimiento(int(input('dd/mm/aaaa: \n')))
U1.set_datos_nacimiento(int(input('edad: \n')))
"""ubicacion"""
print(U1.get_datos_nacimiento())
print()
print('ESTADO CIVIL')
U1.set_estado_civil(str(input('ingrese su estado civil: \n')))
U1.set_estado_civil(int(input('personas a cargo: \n')))
U1.set_estado_civil(str(input('posición familiar: \n')))
U1.set_estado_civil(str(input('libreta militar S/N: ')))
U1.set_estado_civil(str(input('es migrante S/N: ')))
U1.set_estado_civil(str(input('zona rural/urbana: \n')))
print(U1.get_estado_civil())
print()
print('DOMICILIO')
"""Ubicacion"""
print()
print('SISBEN')
U1.set_sisben(str(input('ingrese su tipo de sisben: \n')))
U1.set_sisben(int(input('nivel del sisben: \n')))
U1.set_sisben(int(input('puntaje del sisben: \n')))
U1.set_sisben(int(input('fecha de ingreso al SISBEN: (dd/mm/aaaa) \n')))
"""Ubicacion"""
print(U1.get_sisben())
print()
print('DATOS DE CONTACTO')
U1.set_datos_contacto(int(input('ingrese su numero telefonico: \n')))
U1.set_datos_contacto(input('telefono celular alterno: '))
U1.set_datos_contacto(int(input('numero telefonico: \n')))
U1.set_datos_contacto(input('numero telefonico alterno: '))
U1.set_datos_contacto(input('correo electronico: \n'))
print(U1.get_datos_contacto())
print()
print('SITUACION OCUPACIONAL')
U1.set_situacion_ocupacional(int(input('tiempo que lleva de empleo(meses): ')))
U1.set_situacion_ocupacional(int(input('sueldo que aceptaria: \n $')))
print(U1.get_situacion_ocupacional())